name: Feature Request
description: Suggest a new feature or enhancement for MrWhoOidc
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you've completed these steps before submitting
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have read the [documentation](https://github.com/popicka70/mrwhooidc/tree/main/docs)
          required: true
        - label: I have checked the [roadmap/backlog](https://github.com/popicka70/mrwhooidc/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement)
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - "OIDC Protocol / OAuth 2.0"
        - "Admin UI"
        - "Multi-Tenancy"
        - "Performance / Caching"
        - "Security"
        - "Developer Experience / Integration"
        - "Documentation"
        - "Deployment / Operations"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Nice to have"
        - "Important"
        - "Critical / Blocking"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: |
        Example: As a developer integrating with MrWhoOidc, I need to support device authorization flow (RFC 8628) for IoT devices that don't have web browsers...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: |
        Example: Implement device authorization flow with:
        - /device-authorization endpoint
        - /device-token endpoint
        - User code verification UI in admin
        - Configurable polling interval
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: |
        Example: Considered using existing authorization code flow with a proxy service, but this adds complexity...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who would benefit from this feature? How many users would it impact?
      placeholder: |
        Example: Would benefit IoT device manufacturers, smart TV apps, CLI tools, and embedded systems. Estimated 20-30% of OIDC use cases involve device flow.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details (Optional)
      description: If you have technical implementation ideas, share them here
      placeholder: |
        Example: Could leverage existing token service with new DeviceCodeStore. Would need:
        - New database table for device codes
        - Background service to clean up expired codes
        - UI components in admin for user verification

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to specs, examples, or related projects
      placeholder: |
        Example:
        - RFC 8628: https://datatracker.ietf.org/doc/html/rfc8628
        - Example implementation: https://github.com/...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I can help with testing/validation
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, diagrams, or information
      placeholder: "Example: Attach UI mockups, sequence diagrams, or example requests/responses"
