using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using MrWho.Shared;

namespace MrWho.Models;

/// <summary>
/// Represents a registered device that can be used for authentication by a user
/// </summary>
public class UserDevice
{
    [Key]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// The user this device belongs to
    /// </summary>
    [Required]
    public string UserId { get; set; } = string.Empty;

    /// <summary>
    /// Unique device identifier (generated by the device/app)
    /// </summary>
    [Required]
    [StringLength(500)]
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// User-friendly name for the device
    /// </summary>
    [Required]
    [StringLength(200)]
    public string DeviceName { get; set; } = string.Empty;

    /// <summary>
    /// Type of device (Phone, Tablet, Desktop, etc.)
    /// </summary>
    public DeviceType DeviceType { get; set; } = DeviceType.Unknown;

    /// <summary>
    /// Operating system running on the device
    /// </summary>
    [StringLength(100)]
    public string? OperatingSystem { get; set; }

    /// <summary>
    /// Browser or app information
    /// </summary>
    [StringLength(200)]
    public string? UserAgent { get; set; }

    /// <summary>
    /// Whether this device is trusted for passwordless authentication
    /// </summary>
    public bool IsTrusted { get; set; } = false;

    /// <summary>
    /// Whether this device can be used for QR code approval
    /// </summary>
    public bool CanApproveLogins { get; set; } = true;

    /// <summary>
    /// Whether this device is currently active
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// Security token for push notifications (if supported)
    /// </summary>
    [StringLength(1000)]
    public string? PushToken { get; set; }

    /// <summary>
    /// Public key for device-specific encryption (if supported)
    /// </summary>
    [StringLength(2000)]
    public string? PublicKey { get; set; }

    /// <summary>
    /// Last time this device was used for authentication
    /// </summary>
    public DateTime? LastUsedAt { get; set; }

    /// <summary>
    /// Last known IP address of the device
    /// </summary>
    [StringLength(50)]
    public string? LastIpAddress { get; set; }

    /// <summary>
    /// Last known location/geolocation (if available)
    /// </summary>
    [StringLength(500)]
    public string? LastLocation { get; set; }

    /// <summary>
    /// When this device was first registered
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When this device was last updated
    /// </summary>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When this device expires (if applicable)
    /// </summary>
    public DateTime? ExpiresAt { get; set; }

    /// <summary>
    /// Additional metadata about the device (JSON)
    /// </summary>
    [StringLength(2000)]
    public string? Metadata { get; set; }

    // ===================== AUTO-LOGIN TOKEN (Option 1) =====================
    /// <summary>
    /// Hash of the device auto-login token (base64) if issued. Null when not issued or revoked.
    /// </summary>
    [StringLength(512)]
    public string? DeviceAuthTokenHash { get; set; }

    /// <summary>
    /// Salt used when hashing the device auto-login token (base64). Separate per device token.
    /// </summary>
    [StringLength(256)]
    public string? DeviceAuthTokenSalt { get; set; }

    /// <summary>
    /// Expiration timestamp (UTC) for the device auto-login token. After this time token is invalid.
    /// </summary>
    public DateTime? DeviceAuthTokenExpiresAt { get; set; }

    // Navigation property
    [ForeignKey(nameof(UserId))]
    public virtual IdentityUser User { get; set; } = null!;

    // Navigation properties for device activities
    public virtual ICollection<DeviceAuthenticationLog> AuthenticationLogs { get; set; } = new List<DeviceAuthenticationLog>();
    public virtual ICollection<PersistentQrSession> QrSessions { get; set; } = new List<PersistentQrSession>();
}

/// <summary>
/// Represents a persistent QR code session that can be approved by a registered device
/// </summary>
public class PersistentQrSession
{
    [Key]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// Unique session token displayed in QR code
    /// </summary>
    [Required]
    [StringLength(500)]
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// User who initiated the QR login session
    /// </summary>
    public string? UserId { get; set; }

    /// <summary>
    /// Device that approved this session (if approved)
    /// </summary>
    public string? ApprovedByDeviceId { get; set; }

    /// <summary>
    /// OIDC client requesting authentication
    /// </summary>
    [StringLength(200)]
    public string? ClientId { get; set; }

    /// <summary>
    /// Return URL after successful authentication
    /// </summary>
    [StringLength(2000)]
    public string? ReturnUrl { get; set; }

    /// <summary>
    /// Current status of the QR session
    /// </summary>
    public QrSessionStatus Status { get; set; } = QrSessionStatus.Pending;

    /// <summary>
    /// When this session was created
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When this session expires
    /// </summary>
    public DateTime ExpiresAt { get; set; } = DateTime.UtcNow.AddMinutes(5);

    /// <summary>
    /// When this session was approved (if applicable)
    /// </summary>
    public DateTime? ApprovedAt { get; set; }

    /// <summary>
    /// When this session was completed/used
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// IP address that initiated the session
    /// </summary>
    [StringLength(50)]
    public string? InitiatorIpAddress { get; set; }

    /// <summary>
    /// IP address that approved the session
    /// </summary>
    [StringLength(50)]
    public string? ApproverIpAddress { get; set; }

    /// <summary>
    /// Additional session metadata (JSON)
    /// </summary>
    [StringLength(1000)]
    public string? Metadata { get; set; }

    // Navigation properties
    [ForeignKey(nameof(UserId))]
    public virtual IdentityUser? User { get; set; }

    [ForeignKey(nameof(ApprovedByDeviceId))]
    public virtual UserDevice? ApprovedByDevice { get; set; }
}

/// <summary>
/// Logs device authentication activities for security monitoring
/// </summary>
public class DeviceAuthenticationLog
{
    [Key]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// Device that performed the authentication
    /// </summary>
    [Required]
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// User who was authenticated
    /// </summary>
    [Required]
    public string UserId { get; set; } = string.Empty;

    /// <summary>
    /// Type of authentication activity
    /// </summary>
    public DeviceAuthActivity ActivityType { get; set; }

    /// <summary>
    /// OIDC client involved in the authentication
    /// </summary>
    [StringLength(200)]
    public string? ClientId { get; set; }

    /// <summary>
    /// Whether the activity was successful
    /// </summary>
    public bool IsSuccessful { get; set; } = true;

    /// <summary>
    /// Error message if activity failed
    /// </summary>
    [StringLength(500)]
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// IP address where activity occurred
    /// </summary>
    [StringLength(50)]
    public string? IpAddress { get; set; }

    /// <summary>
    /// User agent string
    /// </summary>
    [StringLength(500)]
    public string? UserAgent { get; set; }

    /// <summary>
    /// When this activity occurred
    /// </summary>
    public DateTime OccurredAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Additional activity metadata (JSON)
    /// </summary>
    [StringLength(1000)]
    public string? Metadata { get; set; }

    // Navigation properties
    [ForeignKey(nameof(DeviceId))]
    public virtual UserDevice Device { get; set; } = null!;

    [ForeignKey(nameof(UserId))]
    public virtual IdentityUser User { get; set; } = null!;
}
