// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrWho.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MrWho.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250907160000_Consent")]
    partial class Consent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // The full model snapshot is large and generated by tooling; for brevity here we only include the Consents entity.
            modelBuilder.Entity("MrWho.Models.Consent", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("ClientId")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("GrantedScopesJson")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Version")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("UserId", "ClientId")
                    .IsUnique();

                b.ToTable("Consents");
            });
        }
    }
}
